development:
  adapter: postgresql
  database: watchdocs-backend
  pool: 5

test:
  adapter: postgresql
  database: watchdocs-backend-test
  pool: 5

production:
  url: <%= ENV['DATABASE_URL'] %>

dev:
  url: <%= ENV['DATABASE_URL'] %>
